In [ ]:
import numpy as np

a=np.array([1,2,3,4])
print(a)



[1 2 3 4]


In [ ]:
b=np.array([[1,2,3,4],[9,8,7,6]])
b

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

type(b)

In [ ]:
b.shape

(2, 4)

In [ ]:
b.size

8

In [ ]:
b.reshape(4,2)

array([[1, 2],
       [3, 4],
       [9, 8],
       [7, 6]])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.sum()

np.int64(10)

In [ ]:
a.prod()

np.int64(24)

In [ ]:
b

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [ ]:
b.sum(axis=0)

array([10, 10, 10, 10])

b.sum(axis=1)

In [ ]:
b[1]

array([9, 8, 7, 6])